AWSTemplateFormatVersion: "2010-09-09"

Description: "All-in-one Amzn Linux2 EC2 instance for testing purposes"

Parameters:
  EnvName:
    Description: Environment Name
    Type: String
    AllowedValues: [dev, prod]
    ConstraintDescription: Must be dev or prod.
  AppName: 
    Description: Application name
    Type: String
  VPCId:
    Description: "VPC to create the SG and EC2 Instance. Must be in ca-central-1, us-east-1, or us-west-2."
    Type: String
  Subnet1:
    Description: "Subnet to deploy the EC2 Instance"
    Type: String
  SGCIDRIngressSSH:
    Description: CIDR Block Ingress for SSH 
    Type: String
    AllowedPattern: ([0-9]{1,3}\.){3}[0-9]{1,3}(\/([0-9]|[1-2][0-9]|3[0-2]))?$
    ConstraintDescription: Must be a valid IP address in the form (x.x.x.x/x)
  SGCIDRIngressICMP:
    Description: CIDR Block Ingress for ICMP 
    Type: String
    AllowedPattern: ([0-9]{1,3}\.){3}[0-9]{1,3}(\/([0-9]|[1-2][0-9]|3[0-2]))?$
    ConstraintDescription: Must be a valid IP address in the form (x.x.x.x/x)
  
Mappings:
  RegionArchAMI:
    ca-central-1:
      HVM64: ami-0fca0f98dc87d39df
    us-east-1:
      HVM64: ami-04d29b6f966df1537
    us-west-2:
      HVM64: ami-0e472933a1395e172
    
  EnvInstanceType:
    dev:
      instanceType: t2.micro
    prod:
      instanceType: t2.small

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !FindInMap [EnvInstanceType, !Ref 'EnvName', instanceType]
      ImageId: !FindInMap [RegionArchAMI, !Ref 'AWS::Region', HVM64]
      SubnetId: !Ref Subnet1
      SecurityGroupIds: 
        - 
          !Ref SSHSecurityGroup
      Tags:
        -
          Key: Name
          Value: !Sub ${AppName} EC2

  SSHSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: !Sub SG for ${AppName}
      SecurityGroupIngress:
        - CidrIp: !Sub ${SGCIDRIngressSSH}
          FromPort: 22
          ToPort: 22
          IpProtocol: tcp
        - CidrIp: !Sub ${SGCIDRIngressICMP}
          IpProtocol: icmp
          FromPort: 8
          ToPort: -1
          
      VpcId: !Ref VPCId


Outputs:
  SSHGroupId:
    Value: !Ref SSHSecurityGroup
    Description: SSH and ICMP Security Group ID